### PR TITLE
Updated coffee.rs

### PR DESCRIPTION
**Pull request by itschiggy**
fix(core): typo fix in error message in the coffee manager

change "this should never happens" to "this should never happen"

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
Thanks, please modify the commit header according to this https://coffee-docs.netlify.app/contributing-to-coffee.html

**Comment by itschiggy** [comment]
Modified with the same, please review

**Comment by vincenzopalazzo** [comment]
>Modified with the same, please review

Modify with the same meaning that you did not modify anything! Please read the contribution guideline

**Comment by itschiggy** [comment]
Sorry mate, it's my first time contributing to a project, guess I modified a comment instead of the actual commit message. I searched a lot on how to edit the actual message, and it looks like the only option was to force push, which is said to make the maintainers job harder, so a sure shot no-no. I guess I'll just leave it here for now and raise a different PR fixing this when I'm done with adding a command I've been working on for coffee.
Thanks!

**Pull request closed without merging**
